In [13]:
import numpy as np
import torch

# numpy

In [3]:
m1 = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [8]:
v1 = np.array([1,2,3])

In [9]:
m1 * v1

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [10]:
m1 - v1

array([[0, 0, 0],
       [3, 3, 3],
       [6, 6, 6]])

In [11]:
m1 + v1

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [12]:
m1 / v1

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ],
       [7. , 4. , 3. ]])

# torch

In [14]:
tm1 = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])

In [15]:
tv1 = torch.tensor([1,2,3])

In [16]:
tm1 * tv1

tensor([[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]])

In [18]:
tm1 - tv1

tensor([[0, 0, 0],
        [3, 3, 3],
        [6, 6, 6]])

In [19]:
tm1 + tv1

tensor([[ 2,  4,  6],
        [ 5,  7,  9],
        [ 8, 10, 12]])

In [20]:
tm1 / tv1

tensor([[1.0000, 1.0000, 1.0000],
        [4.0000, 2.5000, 2.0000],
        [7.0000, 4.0000, 3.0000]])